name: Visual Regression Test

on: [workflow_dispatch]

jobs:
  test-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Selenium Tests
        env:
          CHROME_VERSION: 81.0.4044.129
          WEB_ROOT: https://www.digitale-gesellschaft.ch/
          APP_NAME: digiges-website
          API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
        run: mvn test
